import { Merriweather_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';
import CursorAnimation from '@/components/CursorAnimation';

import '@/styles/globals.scss';

const merriweatherSans = Merriweather_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shaynite',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={merriweatherSans.className}>
        <Navbar />
        {children}
        <CursorAnimation />
      </body>
    </html>
  )
}
